export const films = [
  {
    id: 1,
    title: 'Future vision',
    subtitle: 'Beyond the ordinary',
    duration: 39.102,
    cover: '/media/cover-1.webp',
    src: '/media/film-1.mp4',
  },
  {
    id: 2,
    title: 'Another world',
    subtitle: 'Through the impossible',
    duration: 33.483,
    cover: '/media/cover-2.webp',
    src: '/media/film-2.mp4',
  },
  {
    id: 3,
    title: 'Love in motion',
    subtitle: 'Lyrics into cinema',
    duration: 30.07,
    cover: '/media/cover-3.webp',
    src: '/media/film-3.mp4',
  },
  {
    id: 4,
    title: 'After hours',
    subtitle: 'Light meets rhythm',
    duration: 33.553,
    cover: '/media/cover-4.webp',
    src: '/media/film-4.mp4',
  },
  {
    id: 5,
    title: 'Seeing red',
    subtitle: 'Your song as a movie',
    duration: 30.07,
    cover: '/media/cover-5.webp',
    src: '/media/film-5.mp4',
  },
];
